CREATE TABLE IF NOT EXISTS fees (
    id                              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    organization_id                 UUID NOT NULL,
    billing_entity_id               UUID NOT NULL,
    invoice_id                      UUID,
    charge_id                       UUID,
    subscription_id                 UUID,
    applied_add_on_id               UUID,
    add_on_id                       UUID,
    charge_filter_id                UUID,
    invoiceable_type                VARCHAR,
    invoiceable_id                  UUID,
    true_up_parent_fee_id           UUID,
    fixed_charge_id                 UUID,
    fee_type                        INTEGER,
    payment_status                  INTEGER NOT NULL DEFAULT 0,
    amount_cents                    BIGINT NOT NULL DEFAULT 0,
    amount_currency                 VARCHAR NOT NULL DEFAULT '',
    taxes_amount_cents              BIGINT NOT NULL DEFAULT 0,
    taxes_rate                      DOUBLE PRECISION NOT NULL DEFAULT 0.0,
    precise_amount_cents            NUMERIC(40,15) NOT NULL DEFAULT 0.0,
    taxes_precise_amount_cents      NUMERIC(40,15) NOT NULL DEFAULT 0.0,
    precise_coupons_amount_cents    NUMERIC(30,5) NOT NULL DEFAULT 0.0,
    precise_credit_notes_amount_cents NUMERIC(30,5) NOT NULL DEFAULT 0.0,
    taxes_base_rate                 DOUBLE PRECISION NOT NULL DEFAULT 1.0,
    unit_amount_cents               BIGINT NOT NULL DEFAULT 0,
    precise_unit_amount             NUMERIC(30,15) NOT NULL DEFAULT 0.0,
    units                           NUMERIC NOT NULL DEFAULT 0.0,
    total_aggregated_units          NUMERIC,
    events_count                    INTEGER,
    pay_in_advance                  BOOLEAN NOT NULL DEFAULT FALSE,
    pay_in_advance_event_id         UUID,
    pay_in_advance_event_transaction_id VARCHAR,
    description                     VARCHAR,
    invoice_display_name            VARCHAR,
    properties                      JSONB NOT NULL DEFAULT '{}',
    amount_details                  JSONB NOT NULL DEFAULT '{}',
    grouped_by                      JSONB NOT NULL DEFAULT '{}',
    succeeded_at                    TIMESTAMPTZ,
    failed_at                       TIMESTAMPTZ,
    refunded_at                     TIMESTAMPTZ,
    deleted_at                      TIMESTAMPTZ,
    created_at                      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at                      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_fees_invoice_id ON fees(invoice_id);
CREATE INDEX IF NOT EXISTS idx_fees_organization_id ON fees(organization_id);
CREATE INDEX IF NOT EXISTS idx_fees_subscription_id ON fees(subscription_id);
